/*
 * Copyright 2026 Open Health Stack Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.ohs.fhir.model.r4b

/**
 * GENERATED — not part of the FHIR spec.
 *
 * Every `<Type>Choices` sealed interface here bundles the choice-type option-sets that one model
 * type is a bare member of, so that model class can declare a single supertype instead of a long
 * list of per-field interfaces. They exist purely to keep the generated model headers readable and
 * are an implementation detail — prefer the individual option-set types in code. Each is `sealed`
 * with its model type as the sole subtype, so `when` exhaustiveness is preserved.
 */
public object FhirChoiceParticipants {
  public sealed interface AddressChoices :
    Claim.Accident.Location,
    Claim.Item.Location,
    ClaimResponse.AddItem.Location,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    ExplanationOfBenefit.Accident.Location,
    ExplanationOfBenefit.AddItem.Location,
    ExplanationOfBenefit.Item.Location,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface AgeChoices :
    ActivityDefinition.Timing,
    AllergyIntolerance.Onset,
    Condition.Abatement,
    Condition.Onset,
    FamilyMemberHistory.Age,
    FamilyMemberHistory.Condition.Onset,
    FamilyMemberHistory.Deceased,
    PlanDefinition.Action.Timing,
    Procedure.Performed,
    RequestGroup.Action.Timing

  public sealed interface AnnotationChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface AttachmentChoices :
    AdministrableProductDefinition.Property.Value,
    Citation.CitedArtifact.RelatesTo.Target,
    Citation.RelatesTo.Target,
    Claim.SupportingInfo.Value,
    Communication.Payload.Content,
    CommunicationRequest.Payload.Content,
    Consent.Source,
    Contract.Friendly.Content,
    Contract.Legal.Content,
    Contract.LegallyBinding,
    Contract.Rule.Content,
    Contract.Term.Offer.Answer.Value,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    ExplanationOfBenefit.SupportingInfo.Value,
    Extension.Value,
    ManufacturedItemDefinition.Property.Value,
    MedicinalProductDefinition.Characteristic.Value,
    NutritionProduct.ProductCharacteristic.Value,
    PackagedProductDefinition.Package.Property.Value,
    Parameters.Parameter.Value,
    Questionnaire.Item.Initial.Value,
    QuestionnaireResponse.Item.Answer.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    SubstanceDefinition.Property.Value,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface Base64BinaryChoices :
    AuditEvent.Entity.Detail.Value,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    MedicationKnowledge.DrugCharacteristic.Value,
    NutritionProduct.ProductCharacteristic.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface BooleanChoices :
    AdministrableProductDefinition.Property.Value,
    Claim.SupportingInfo.Value,
    CodeSystem.Concept.Property.Value,
    Contract.Term.Offer.Answer.Value,
    DeviceRequest.Parameter.Value,
    Dosage.AsNeeded,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    EvidenceReport.Subject.Characteristic.Value,
    ExplanationOfBenefit.SupportingInfo.Value,
    Extension.Value,
    FamilyMemberHistory.Deceased,
    Goal.Target.Detail,
    Group.Characteristic.Value,
    ImplementationGuide.Definition.Resource.Example,
    ImplementationGuide.Manifest.Resource.Example,
    ManufacturedItemDefinition.Property.Value,
    MedicationRequest.Reported,
    MedicationRequest.Substitution.Allowed,
    MedicinalProductDefinition.Characteristic.Value,
    NutritionProduct.ProductCharacteristic.Value,
    Observation.Component.Value,
    Observation.Value,
    PackagedProductDefinition.Package.Property.Value,
    Parameters.Parameter.Value,
    Patient.Deceased,
    Patient.MultipleBirth,
    Questionnaire.Item.EnableWhen.Answer,
    Questionnaire.Item.Initial.Value,
    QuestionnaireResponse.Item.Answer.Value,
    ServiceRequest.AsNeeded,
    StructureMap.Group.Rule.Source.DefaultValue,
    StructureMap.Group.Rule.Target.Parameter.Value,
    SubstanceDefinition.Property.Value,
    SupplyRequest.Parameter.Value,
    Task.Input.Value,
    Task.Output.Value,
    ValueSet.Expansion.Parameter.Value

  public sealed interface CanonicalChoices :
    ActivityDefinition.Subject,
    EvidenceVariable.Characteristic.Definition,
    ImplementationGuide.Definition.Resource.Example,
    ImplementationGuide.Manifest.Resource.Example,
    PlanDefinition.Action.Subject,
    PlanDefinition.Subject,
    ResearchElementDefinition.Characteristic.Definition

  public sealed interface CodeableConceptChoices :
    ActivityDefinition.Product,
    ActivityDefinition.Subject,
    AdministrableProductDefinition.Property.Value,
    CarePlan.Activity.Detail.Product,
    ChargeItem.Product,
    Claim.Diagnosis.Diagnosis,
    Claim.Item.Location,
    Claim.Procedure.Procedure,
    ClaimResponse.AddItem.Location,
    ClinicalUseDefinition.Interaction.Interactant.Item,
    Contract.Term.Asset.ValuedItem.Entity,
    Contract.Term.Topic,
    Contract.Topic,
    CoverageEligibilityRequest.Item.Diagnosis.Diagnosis,
    DataRequirement.Subject,
    DeviceRequest.Code,
    DeviceRequest.Parameter.Value,
    Dosage.AsNeeded,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    EventDefinition.Subject,
    EvidenceReport.Subject.Characteristic.Value,
    EvidenceVariable.Category.Value,
    EvidenceVariable.Characteristic.Definition,
    ExplanationOfBenefit.AddItem.Location,
    ExplanationOfBenefit.Diagnosis.Diagnosis,
    ExplanationOfBenefit.Item.Location,
    ExplanationOfBenefit.Procedure.Procedure,
    Extension.Value,
    Goal.Start,
    Goal.Target.Detail,
    Group.Characteristic.Value,
    GuidanceResponse.Module,
    Invoice.LineItem.ChargeItem,
    Library.Subject,
    ManufacturedItemDefinition.Property.Value,
    Measure.Subject,
    Medication.Ingredient.Item,
    MedicationAdministration.Medication,
    MedicationDispense.Medication,
    MedicationDispense.StatusReason,
    MedicationKnowledge.AdministrationGuidelines.Indication,
    MedicationKnowledge.AdministrationGuidelines.PatientCharacteristics.Characteristic,
    MedicationKnowledge.DrugCharacteristic.Value,
    MedicationKnowledge.Ingredient.Item,
    MedicationRequest.Medication,
    MedicationRequest.Substitution.Allowed,
    MedicationStatement.Medication,
    MedicinalProductDefinition.Characteristic.Value,
    NutritionProduct.ProductCharacteristic.Value,
    Observation.Component.Value,
    Observation.Value,
    PackagedProductDefinition.Package.Property.Value,
    Parameters.Parameter.Value,
    PlanDefinition.Action.Subject,
    PlanDefinition.Goal.Target.Detail,
    PlanDefinition.Subject,
    Population.Age,
    ResearchDefinition.Subject,
    ResearchElementDefinition.Characteristic.Definition,
    ResearchElementDefinition.Subject,
    ServiceRequest.AsNeeded,
    Specimen.Collection.FastingStatus,
    Specimen.Container.Additive,
    SpecimenDefinition.TypeTested.Container.Additive.Additive,
    StructureMap.Group.Rule.Source.DefaultValue,
    Substance.Ingredient.Substance,
    SubstanceDefinition.Property.Value,
    SubstanceDefinition.Relationship.SubstanceDefinition,
    SupplyDelivery.SuppliedItem.Item,
    SupplyRequest.Item,
    SupplyRequest.Parameter.Value,
    Task.Input.Value,
    Task.Output.Value,
    UsageContext.Value

  public sealed interface CodeableReferenceChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value

  public sealed interface CodingChoices :
    CodeSystem.Concept.Property.Value,
    Contract.Term.Offer.Answer.Value,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    MessageDefinition.Event,
    MessageHeader.Event,
    Parameters.Parameter.Value,
    Questionnaire.Item.AnswerOption.Value,
    Questionnaire.Item.EnableWhen.Answer,
    Questionnaire.Item.Initial.Value,
    QuestionnaireResponse.Item.Answer.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface ContactDetailChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface ContactPointChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface ContributorChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface DataRequirementChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Parameters.Parameter.Value,
    ResearchElementDefinition.Characteristic.Definition,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface DateChoices :
    AdministrableProductDefinition.Property.Value,
    Claim.Item.Serviced,
    Claim.SupportingInfo.Timing,
    ClaimResponse.AddItem.Serviced,
    Contract.Term.Offer.Answer.Value,
    CoverageEligibilityRequest.Serviced,
    CoverageEligibilityResponse.Serviced,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.MaxValue,
    ElementDefinition.MinValue,
    ElementDefinition.Pattern,
    ExplanationOfBenefit.AddItem.Serviced,
    ExplanationOfBenefit.Item.Serviced,
    ExplanationOfBenefit.SupportingInfo.Timing,
    Extension.Value,
    FamilyMemberHistory.Born,
    FamilyMemberHistory.Deceased,
    Goal.Start,
    Goal.Target.Due,
    ManufacturedItemDefinition.Property.Value,
    MedicinalProductDefinition.Characteristic.Value,
    PackagedProductDefinition.Package.Property.Value,
    Parameters.Parameter.Value,
    Questionnaire.Item.AnswerOption.Value,
    Questionnaire.Item.EnableWhen.Answer,
    Questionnaire.Item.Initial.Value,
    QuestionnaireResponse.Item.Answer.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    SubstanceDefinition.Property.Value,
    Task.Input.Value,
    Task.Output.Value,
    TriggerDefinition.Timing

  public sealed interface DateTimeChoices :
    ActivityDefinition.Timing,
    AllergyIntolerance.Onset,
    BiologicallyDerivedProduct.Collection.Collected,
    BiologicallyDerivedProduct.Manipulation.Time,
    BiologicallyDerivedProduct.Processing.Time,
    ChargeItem.Occurrence,
    ClinicalImpression.Effective,
    CodeSystem.Concept.Property.Value,
    CommunicationRequest.Occurrence,
    Condition.Abatement,
    Condition.Onset,
    Contract.Term.Action.Occurrence,
    Contract.Term.Offer.Answer.Value,
    DataRequirement.DateFilter.Value,
    DetectedIssue.Identified,
    DeviceRequest.Occurrence,
    DeviceUseStatement.Timing,
    DiagnosticReport.Effective,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.MaxValue,
    ElementDefinition.MinValue,
    ElementDefinition.Pattern,
    Extension.Value,
    Immunization.Occurrence,
    Media.Created,
    MedicationAdministration.Effective,
    MedicationStatement.Effective,
    Observation.Component.Value,
    Observation.Effective,
    Observation.Value,
    Parameters.Parameter.Value,
    Patient.Deceased,
    PlanDefinition.Action.Timing,
    Procedure.Performed,
    Provenance.Occurred,
    Questionnaire.Item.EnableWhen.Answer,
    Questionnaire.Item.Initial.Value,
    QuestionnaireResponse.Item.Answer.Value,
    RegulatedAuthorization.Case.Date,
    RequestGroup.Action.Timing,
    ResearchElementDefinition.Characteristic.ParticipantEffective,
    ResearchElementDefinition.Characteristic.StudyEffective,
    RiskAssessment.Occurrence,
    ServiceRequest.Occurrence,
    Specimen.Collection.Collected,
    Specimen.Processing.Time,
    StructureMap.Group.Rule.Source.DefaultValue,
    SupplyDelivery.Occurrence,
    SupplyRequest.Occurrence,
    Task.Input.Value,
    Task.Output.Value,
    TriggerDefinition.Timing,
    ValueSet.Expansion.Parameter.Value

  public sealed interface DecimalChoices :
    CodeSystem.Concept.Property.Value,
    Contract.Term.Offer.Answer.Value,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.MaxValue,
    ElementDefinition.MinValue,
    ElementDefinition.Pattern,
    Extension.Value,
    Parameters.Parameter.Value,
    Questionnaire.Item.EnableWhen.Answer,
    Questionnaire.Item.Initial.Value,
    QuestionnaireResponse.Item.Answer.Value,
    RiskAssessment.Prediction.Probability,
    StructureMap.Group.Rule.Source.DefaultValue,
    StructureMap.Group.Rule.Target.Parameter.Value,
    Task.Input.Value,
    Task.Output.Value,
    ValueSet.Expansion.Parameter.Value

  public sealed interface DosageChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface DurationChoices :
    ActivityDefinition.Timing,
    DataRequirement.DateFilter.Value,
    Goal.Target.Due,
    PackagedProductDefinition.Package.ShelfLifeStorage.Period,
    PlanDefinition.Action.RelatedAction.Offset,
    PlanDefinition.Action.Timing,
    RequestGroup.Action.RelatedAction.Offset,
    RequestGroup.Action.Timing,
    ResearchElementDefinition.Characteristic.ParticipantEffective,
    ResearchElementDefinition.Characteristic.StudyEffective,
    Specimen.Collection.FastingStatus,
    Timing.Repeat.Bounds

  public sealed interface ExpressionChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    EvidenceVariable.Characteristic.Definition,
    Extension.Value,
    Parameters.Parameter.Value,
    ResearchElementDefinition.Characteristic.Definition,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface HumanNameChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface IdentifierChoices :
    Citation.CitedArtifact.RelatesTo.Target,
    Citation.RelatesTo.Target,
    Composition.RelatesTo.Target,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    EvidenceReport.RelatesTo.Target,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface InstantChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.MaxValue,
    ElementDefinition.MinValue,
    ElementDefinition.Pattern,
    Extension.Value,
    Observation.Effective,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface IntegerChoices :
    CodeSystem.Concept.Property.Value,
    Contract.Term.Offer.Answer.Value,
    Goal.Target.Detail,
    Observation.Component.Value,
    Observation.Value,
    Patient.MultipleBirth,
    Questionnaire.Item.AnswerOption.Value,
    Questionnaire.Item.EnableWhen.Answer,
    Questionnaire.Item.Initial.Value,
    QuestionnaireResponse.Item.Answer.Value,
    StructureMap.Group.Rule.Target.Parameter.Value,
    ValueSet.Expansion.Parameter.Value

  public sealed interface MarkdownChoices : Evidence.CiteAs, EvidenceReport.CiteAs

  public sealed interface MetaChoices :
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface MoneyChoices :
    Coverage.CostToBeneficiary.Value,
    CoverageEligibilityResponse.Insurance.Item.Benefit.Allowed,
    CoverageEligibilityResponse.Insurance.Item.Benefit.Used,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    ExplanationOfBenefit.BenefitBalance.Financial.Allowed,
    ExplanationOfBenefit.BenefitBalance.Financial.Used,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface ParameterDefinitionChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface PeriodChoices :
    ActivityDefinition.Timing,
    AllergyIntolerance.Onset,
    BiologicallyDerivedProduct.Collection.Collected,
    BiologicallyDerivedProduct.Manipulation.Time,
    BiologicallyDerivedProduct.Processing.Time,
    CarePlan.Activity.Detail.Scheduled,
    ChargeItem.Occurrence,
    Claim.Item.Serviced,
    Claim.SupportingInfo.Timing,
    ClaimResponse.AddItem.Serviced,
    ClinicalImpression.Effective,
    CommunicationRequest.Occurrence,
    Condition.Abatement,
    Condition.Onset,
    Contract.Term.Action.Occurrence,
    CoverageEligibilityRequest.Serviced,
    CoverageEligibilityResponse.Serviced,
    DataRequirement.DateFilter.Value,
    DetectedIssue.Identified,
    DeviceRequest.Occurrence,
    DeviceUseStatement.Timing,
    DiagnosticReport.Effective,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    ExplanationOfBenefit.AddItem.Serviced,
    ExplanationOfBenefit.Item.Serviced,
    ExplanationOfBenefit.SupportingInfo.Timing,
    Extension.Value,
    FamilyMemberHistory.Born,
    FamilyMemberHistory.Condition.Onset,
    Media.Created,
    MedicationAdministration.Effective,
    MedicationStatement.Effective,
    Observation.Component.Value,
    Observation.Effective,
    Observation.Value,
    Parameters.Parameter.Value,
    PlanDefinition.Action.Timing,
    Procedure.Performed,
    Provenance.Occurred,
    RegulatedAuthorization.Case.Date,
    RequestGroup.Action.Timing,
    ResearchElementDefinition.Characteristic.ParticipantEffective,
    ResearchElementDefinition.Characteristic.StudyEffective,
    RiskAssessment.Occurrence,
    RiskAssessment.Prediction.When,
    ServiceRequest.Occurrence,
    Specimen.Collection.Collected,
    Specimen.Processing.Time,
    StructureMap.Group.Rule.Source.DefaultValue,
    SupplyDelivery.Occurrence,
    SupplyRequest.Occurrence,
    Task.Input.Value,
    Task.Output.Value,
    Timing.Repeat.Bounds

  public sealed interface PositiveIntChoices :
    Immunization.ProtocolApplied.DoseNumber,
    Immunization.ProtocolApplied.SeriesDoses,
    ImmunizationEvaluation.DoseNumber,
    ImmunizationEvaluation.SeriesDoses,
    ImmunizationRecommendation.Recommendation.DoseNumber,
    ImmunizationRecommendation.Recommendation.SeriesDoses

  public sealed interface QuantityChoices :
    AdministrableProductDefinition.Property.Value,
    Claim.SupportingInfo.Value,
    Contract.Term.Offer.Answer.Value,
    Coverage.CostToBeneficiary.Value,
    DeviceRequest.Parameter.Value,
    Dosage.DoseAndRate.Dose,
    Dosage.DoseAndRate.Rate,
    ElementDefinition.MaxValue,
    ElementDefinition.MinValue,
    EvidenceReport.Subject.Characteristic.Value,
    EvidenceVariable.Category.Value,
    ExplanationOfBenefit.SupportingInfo.Value,
    Goal.Target.Detail,
    Group.Characteristic.Value,
    ManufacturedItemDefinition.Property.Value,
    MedicationAdministration.Dosage.Rate,
    MedicationKnowledge.AdministrationGuidelines.PatientCharacteristics.Characteristic,
    MedicationKnowledge.DrugCharacteristic.Value,
    MedicinalProductDefinition.Characteristic.Value,
    NutritionOrder.EnteralFormula.Administration.Rate,
    NutritionProduct.ProductCharacteristic.Value,
    Observation.Component.Value,
    Observation.Value,
    PackagedProductDefinition.Package.Property.Value,
    PlanDefinition.Goal.Target.Detail,
    Questionnaire.Item.EnableWhen.Answer,
    Questionnaire.Item.Initial.Value,
    QuestionnaireResponse.Item.Answer.Value,
    ServiceRequest.Quantity,
    SpecimenDefinition.TypeTested.Container.MinimumVolume,
    SubstanceDefinition.Moiety.Amount,
    SubstanceDefinition.Property.Value,
    SubstanceDefinition.Relationship.Amount,
    SupplyRequest.Parameter.Value,
    UsageContext.Value

  public sealed interface RangeChoices :
    ActivityDefinition.Timing,
    AllergyIntolerance.Onset,
    ClinicalUseDefinition.Indication.Duration,
    Condition.Abatement,
    Condition.Onset,
    DeviceRequest.Parameter.Value,
    Dosage.DoseAndRate.Dose,
    Dosage.DoseAndRate.Rate,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    EvidenceReport.Subject.Characteristic.Value,
    EvidenceVariable.Category.Value,
    Extension.Value,
    FamilyMemberHistory.Age,
    FamilyMemberHistory.Condition.Onset,
    FamilyMemberHistory.Deceased,
    Goal.Target.Detail,
    Group.Characteristic.Value,
    Observation.Component.Value,
    Observation.Value,
    Parameters.Parameter.Value,
    PlanDefinition.Action.RelatedAction.Offset,
    PlanDefinition.Action.Timing,
    PlanDefinition.Goal.Target.Detail,
    Population.Age,
    Procedure.Performed,
    RequestGroup.Action.RelatedAction.Offset,
    RequestGroup.Action.Timing,
    RiskAssessment.Prediction.Probability,
    RiskAssessment.Prediction.When,
    ServiceRequest.Quantity,
    StructureMap.Group.Rule.Source.DefaultValue,
    SupplyRequest.Parameter.Value,
    Task.Input.Value,
    Task.Output.Value,
    Timing.Repeat.Bounds,
    UsageContext.Value

  public sealed interface RatioChoices :
    Dosage.DoseAndRate.Rate,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Goal.Target.Detail,
    Ingredient.Substance.Strength.Concentration,
    Ingredient.Substance.Strength.Presentation,
    Ingredient.Substance.Strength.ReferenceStrength.Strength,
    MedicationAdministration.Dosage.Rate,
    NutritionOrder.EnteralFormula.Administration.Rate,
    Observation.Component.Value,
    Observation.Value,
    Parameters.Parameter.Value,
    ServiceRequest.Quantity,
    StructureMap.Group.Rule.Source.DefaultValue,
    SubstanceDefinition.Relationship.Amount,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface RatioRangeChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Ingredient.Substance.Strength.Concentration,
    Ingredient.Substance.Strength.Presentation,
    Ingredient.Substance.Strength.ReferenceStrength.Strength

  public sealed interface ReferenceChoices :
    ActivityDefinition.Product,
    ActivityDefinition.Subject,
    Annotation.Author,
    CarePlan.Activity.Detail.Product,
    ChargeItem.Product,
    Citation.CitedArtifact.RelatesTo.Target,
    Citation.RelatesTo.Target,
    Claim.Accident.Location,
    Claim.Diagnosis.Diagnosis,
    Claim.Item.Location,
    Claim.Procedure.Procedure,
    Claim.SupportingInfo.Value,
    ClaimResponse.AddItem.Location,
    ClinicalUseDefinition.Interaction.Interactant.Item,
    Communication.Payload.Content,
    CommunicationRequest.Payload.Content,
    Composition.RelatesTo.Target,
    Consent.Source,
    Contract.Friendly.Content,
    Contract.Legal.Content,
    Contract.LegallyBinding,
    Contract.Rule.Content,
    Contract.Term.Asset.ValuedItem.Entity,
    Contract.Term.Offer.Answer.Value,
    Contract.Term.Topic,
    Contract.Topic,
    CoverageEligibilityRequest.Item.Diagnosis.Diagnosis,
    DataRequirement.Subject,
    DeviceDefinition.Manufacturer,
    DeviceRequest.Code,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    EventDefinition.Subject,
    Evidence.CiteAs,
    EvidenceReport.CiteAs,
    EvidenceReport.RelatesTo.Target,
    EvidenceReport.Subject.Characteristic.Value,
    EvidenceVariable.Characteristic.Definition,
    ExplanationOfBenefit.Accident.Location,
    ExplanationOfBenefit.AddItem.Location,
    ExplanationOfBenefit.Diagnosis.Diagnosis,
    ExplanationOfBenefit.Item.Location,
    ExplanationOfBenefit.Procedure.Procedure,
    ExplanationOfBenefit.SupportingInfo.Value,
    Extension.Value,
    Group.Characteristic.Value,
    ImplementationGuide.Definition.Page.Name,
    Invoice.LineItem.ChargeItem,
    Library.Subject,
    Measure.Subject,
    Medication.Ingredient.Item,
    MedicationAdministration.Medication,
    MedicationDispense.Medication,
    MedicationDispense.StatusReason,
    MedicationKnowledge.AdministrationGuidelines.Indication,
    MedicationKnowledge.Ingredient.Item,
    MedicationRequest.Medication,
    MedicationRequest.Reported,
    MedicationStatement.Medication,
    Parameters.Parameter.Value,
    PlanDefinition.Action.Subject,
    PlanDefinition.Subject,
    Questionnaire.Item.AnswerOption.Value,
    Questionnaire.Item.EnableWhen.Answer,
    Questionnaire.Item.Initial.Value,
    QuestionnaireResponse.Item.Answer.Value,
    ResearchDefinition.Subject,
    ResearchElementDefinition.Subject,
    Specimen.Container.Additive,
    SpecimenDefinition.TypeTested.Container.Additive.Additive,
    StructureMap.Group.Rule.Source.DefaultValue,
    Substance.Ingredient.Substance,
    SubstanceDefinition.Relationship.SubstanceDefinition,
    SupplyDelivery.SuppliedItem.Item,
    SupplyRequest.Item,
    Task.Input.Value,
    Task.Output.Value,
    TriggerDefinition.Timing,
    UsageContext.Value

  public sealed interface RelatedArtifactChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface SampledDataChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Observation.Component.Value,
    Observation.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface SignatureChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface StringChoices :
    AllergyIntolerance.Onset,
    Annotation.Author,
    AuditEvent.Entity.Detail.Value,
    CarePlan.Activity.Detail.Scheduled,
    Claim.SupportingInfo.Value,
    ClinicalUseDefinition.Indication.Duration,
    Communication.Payload.Content,
    CommunicationRequest.Payload.Content,
    Condition.Abatement,
    Condition.Onset,
    Contract.Term.Offer.Answer.Value,
    CoverageEligibilityResponse.Insurance.Item.Benefit.Allowed,
    CoverageEligibilityResponse.Insurance.Item.Benefit.Used,
    DeviceDefinition.Manufacturer,
    ExplanationOfBenefit.BenefitBalance.Financial.Allowed,
    ExplanationOfBenefit.SupportingInfo.Value,
    FamilyMemberHistory.Age,
    FamilyMemberHistory.Born,
    FamilyMemberHistory.Condition.Onset,
    FamilyMemberHistory.Deceased,
    Goal.Target.Detail,
    Immunization.Occurrence,
    Immunization.ProtocolApplied.DoseNumber,
    Immunization.ProtocolApplied.SeriesDoses,
    ImmunizationEvaluation.DoseNumber,
    ImmunizationEvaluation.SeriesDoses,
    ImmunizationRecommendation.Recommendation.DoseNumber,
    ImmunizationRecommendation.Recommendation.SeriesDoses,
    MedicationKnowledge.DrugCharacteristic.Value,
    NutritionProduct.ProductCharacteristic.Value,
    Observation.Component.Value,
    Observation.Value,
    PackagedProductDefinition.Package.ShelfLifeStorage.Period,
    Procedure.Performed,
    Questionnaire.Item.AnswerOption.Value,
    Questionnaire.Item.EnableWhen.Answer,
    Questionnaire.Item.Initial.Value,
    QuestionnaireResponse.Item.Answer.Value,
    SpecimenDefinition.TypeTested.Container.MinimumVolume,
    SubstanceDefinition.Moiety.Amount,
    SubstanceDefinition.Relationship.Amount

  public sealed interface TimeChoices :
    Contract.Term.Offer.Answer.Value,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.MaxValue,
    ElementDefinition.MinValue,
    ElementDefinition.Pattern,
    Extension.Value,
    Observation.Component.Value,
    Observation.Value,
    Parameters.Parameter.Value,
    Questionnaire.Item.AnswerOption.Value,
    Questionnaire.Item.EnableWhen.Answer,
    Questionnaire.Item.Initial.Value,
    QuestionnaireResponse.Item.Answer.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface TimingChoices :
    ActivityDefinition.Timing,
    CarePlan.Activity.Detail.Scheduled,
    ChargeItem.Occurrence,
    Contract.Term.Action.Occurrence,
    DeviceRequest.Occurrence,
    DeviceUseStatement.Timing,
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Observation.Effective,
    Parameters.Parameter.Value,
    PlanDefinition.Action.Timing,
    RequestGroup.Action.Timing,
    ResearchElementDefinition.Characteristic.ParticipantEffective,
    ResearchElementDefinition.Characteristic.StudyEffective,
    ServiceRequest.Occurrence,
    StructureMap.Group.Rule.Source.DefaultValue,
    SupplyDelivery.Occurrence,
    SupplyRequest.Occurrence,
    Task.Input.Value,
    Task.Output.Value,
    TriggerDefinition.Timing

  public sealed interface TriggerDefinitionChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value

  public sealed interface UnsignedIntChoices :
    CoverageEligibilityResponse.Insurance.Item.Benefit.Allowed,
    CoverageEligibilityResponse.Insurance.Item.Benefit.Used,
    ExplanationOfBenefit.BenefitBalance.Financial.Allowed,
    ExplanationOfBenefit.BenefitBalance.Financial.Used

  public sealed interface UriChoices :
    Citation.CitedArtifact.RelatesTo.Target,
    Citation.RelatesTo.Target,
    Contract.Term.Offer.Answer.Value,
    MessageDefinition.Event,
    MessageHeader.Event,
    Questionnaire.Item.Initial.Value,
    QuestionnaireResponse.Item.Answer.Value,
    ValueSet.Expansion.Parameter.Value

  public sealed interface UsageContextChoices :
    ElementDefinition.DefaultValue,
    ElementDefinition.Example.Value,
    ElementDefinition.Fixed,
    ElementDefinition.Pattern,
    Extension.Value,
    Parameters.Parameter.Value,
    StructureMap.Group.Rule.Source.DefaultValue,
    Task.Input.Value,
    Task.Output.Value
}
